#!/usr/bin/with-contenv bash

make_dir() {
    echo "make some directory..."
    if [ ! -d /data/cache ]; then
        mkdir /data/cache
    fi
    if [ ! -d /data/certs ]; then
        mkdir /data/certs
    fi
    if [ ! -d /data/config ]; then
        mkdir /data/config
    fi
    if [ ! -d /data/data/logs ]; then
        mkdir -p /data/data/logs
    fi
    if [ ! -d /data/downloads ]; then
        mkdir /data/downloads
    fi
    if [ ! -d /data/temp ]; then
        mkdir /data/temp
    fi
    if [ ! -d /data/torrents ]; then
        mkdir /data/torrents
    fi
    if [ ! -d /data/watch ]; then
        mkdir /data/watch
    fi
    if [ ! -d /data/webui ]; then
        mkdir /data/webui
    fi
    if [ ! -d ${QBITTORRENT_HOME}/qBittorrent ]; then
        mkdir -p ${QBITTORRENT_HOME}/qBittorrent
    fi
    if [ -d ${QBITTORRENT_HOME}/qBittorrent/cache ] && [[ $(readlink -f ${QBITTORRENT_HOME}/qBittorrent/cache) != /data/cache  ]]; then
        rm -rf ${QBITTORRENT_HOME}/qBittorrent/cache
    fi
    if [ -d ${QBITTORRENT_HOME}/qBittorrent/config ] && [[ $(readlink -f ${QBITTORRENT_HOME}/qBittorrent/config) != /data/config  ]]; then
        rm -rf ${QBITTORRENT_HOME}/qBittorrent/config
    fi
    if [ -d ${QBITTORRENT_HOME}/qBittorrent/data ] && [[ $(readlink -f ${QBITTORRENT_HOME}/qBittorrent/data) != /data/data  ]]; then
        rm -rf ${QBITTORRENT_HOME}/qBittorrent/data
    fi
    if [ -d /data/logs ] && [[ $(readlink -f /data/logs) != /data/data/logs  ]]; then
        rm -rf /data/logs
    fi
    ln -sf /data/cache ${QBITTORRENT_HOME}/qBittorrent/cache
    ln -sf /data/config ${QBITTORRENT_HOME}/qBittorrent/config
    ln -sf /data/data ${QBITTORRENT_HOME}/qBittorrent/data
    cd /data
    ln -sf data/logs logs
}

make_dir 2>&1 | sed "s#^#[cont-init.d] $(basename $0): \1#g"
