#!/usr/bin/with-contenv bash

if [[ -z ${CRON_HEALTH_CHECK} ]]; then
    CRON_HEALTH_CHECK="18 * * * *"
fi

if [[ -z ${CRON_AUTO_CATEGORY} ]]; then
    CRON_AUTO_CATEGORY="38 * * * *"
fi

echo -e "${CRON_HEALTH_CHECK} health-check\n${CRON_AUTO_CATEGORY} auto-cat" | crontab -
